version: 2.1

jobs:

  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
    docker:
      - image: cimg/base:2020.09
    working_directory: /tmp/src/aslprep_build
    steps:
      - checkout
      - setup_remote_docker:
         version: docker24

      - run:
          name: Build aslprep_build
          no_output_timeout: 5h
          command: |
            TAG=main
            if [[ -n "$CIRCLE_TAG" ]]; then
              TAG="${CIRCLE_TAG}"
            fi
            DOCKER_BUILDKIT=1 \
            BUILDKIT_PROGRESS=plain \
            docker build -t pennlinc/aslprep_build:${TAG} .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push pennlinc/aslprep_build:$TAG
            

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/